# Generated by Django 3.0.2 on 2020-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=200)),
                ('eemail', models.CharField(max_length=100)),
                ('econtact', models.CharField(max_length=90)),
            ],
        ),
    ]
